<a href="https://colab.research.google.com/github/jongoh-Jeong/MachineLearning-for-AI/blob/main/3%EC%A3%BC%EC%B0%A8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Practice for online lecture

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [3]:
import os
import sys

os.listdir()


['.config', 'drive', 'sample_data']

In [4]:
cd drive/MyDrive/Hands-On-Data-Analysis-with-Pandas-2nd-edition/ch_02

/content/drive/MyDrive/Hands-On-Data-Analysis-with-Pandas-2nd-edition/ch_02


In [5]:
import numpy as np

data = np.genfromtxt(
    'data/example_data.csv',delimiter=';',
     names = True, dtype = None, encoding = 'UTF'
     )

data

array([('2018-10-13 11:10:23.560', '262km NW of Ozernovskiy, Russia', 'mww', 6.7, 'green', 1),
       ('2018-10-13 04:34:15.580', '25km E of Bitung, Indonesia', 'mww', 5.2, 'green', 0),
       ('2018-10-13 00:13:46.220', '42km WNW of Sola, Vanuatu', 'mww', 5.7, 'green', 0),
       ('2018-10-12 21:09:49.240', '13km E of Nueva Concepcion, Guatemala', 'mww', 5.7, 'green', 0),
       ('2018-10-12 02:52:03.620', '128km SE of Kimbe, Papua New Guinea', 'mww', 5.6, 'green', 1)],
      dtype=[('time', '<U23'), ('place', '<U37'), ('magType', '<U3'), ('mag', '<f8'), ('alert', '<U5'), ('tsunami', '<i8')])

In [6]:
data.shape

(5,)

In [7]:
data.dtype

dtype([('time', '<U23'), ('place', '<U37'), ('magType', '<U3'), ('mag', '<f8'), ('alert', '<U5'), ('tsunami', '<i8')])

In [8]:
%%timeit
max(row[3] for row in data)

4.02 µs ± 103 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [9]:
array_dict = {
    col : np.array([row[i] for row in data])
    for i,col in enumerate(data.dtype.names)
}

array_dict

{'time': array(['2018-10-13 11:10:23.560', '2018-10-13 04:34:15.580',
        '2018-10-13 00:13:46.220', '2018-10-12 21:09:49.240',
        '2018-10-12 02:52:03.620'], dtype='<U23'),
 'place': array(['262km NW of Ozernovskiy, Russia', '25km E of Bitung, Indonesia',
        '42km WNW of Sola, Vanuatu',
        '13km E of Nueva Concepcion, Guatemala',
        '128km SE of Kimbe, Papua New Guinea'], dtype='<U37'),
 'magType': array(['mww', 'mww', 'mww', 'mww', 'mww'], dtype='<U3'),
 'mag': array([6.7, 5.2, 5.7, 5.7, 5.6]),
 'alert': array(['green', 'green', 'green', 'green', 'green'], dtype='<U5'),
 'tsunami': array([1, 0, 0, 0, 1])}

In [10]:
array_dict['mag']

array([6.7, 5.2, 5.7, 5.7, 5.6])

In [11]:
array_dict['mag'].argmax()

0

In [12]:
np.array([
    value[array_dict['mag'].argmax()]
    for key,value in array_dict.items()
])

array(['2018-10-13 11:10:23.560', '262km NW of Ozernovskiy, Russia',
       'mww', '6.7', 'green', '1'], dtype='<U32')

In [13]:
import pandas as pd

place = pd.Series(array_dict['place'],name = 'place')
place

0          262km NW of Ozernovskiy, Russia
1              25km E of Bitung, Indonesia
2                42km WNW of Sola, Vanuatu
3    13km E of Nueva Concepcion, Guatemala
4      128km SE of Kimbe, Papua New Guinea
Name: place, dtype: object

In [14]:
place_index = place.index
place_index

RangeIndex(start=0, stop=5, step=1)

In [15]:
place_index.values

array([0, 1, 2, 3, 4])

In [16]:
pwd

'/content/drive/MyDrive/Hands-On-Data-Analysis-with-Pandas-2nd-edition/ch_02'

In [17]:
df = pd.read_csv('data/earthquakes.csv')

In [18]:
df.describe()

cdi         dmin        felt          gap          mag  \
count  329.000000  6139.000000  329.000000  6164.000000  9331.000000   
mean     2.754711     0.544925   12.310030   121.506588     1.497345   
std      1.010637     2.214305   48.954944    72.962363     1.203347   
min      0.000000     0.000648    0.000000    12.000000    -1.260000   
25%      2.000000     0.020425    1.000000    66.142500     0.720000   
50%      2.700000     0.059050    2.000000   105.000000     1.300000   
75%      3.300000     0.177250    5.000000   159.000000     1.900000   
max      8.400000    53.737000  580.000000   355.910000     7.500000   

             mmi          nst          rms          sig          time  \
count  93.000000  5364.000000  9332.000000  9332.000000  9.332000e+03   
mean    3.651398    19.053878     0.362122    56.899914  1.538284e+12   
std     1.790523    15.492315     0.317784    91.872163  6.080306e+08   
min     0.000000     0.000000     0.000000     0.000000  1.537229e+12   
25%     2.680000     8.000000     0.119675     8.000000  1.537793e+12   
50%     3.720000    15.000000     0.210000    26.000000  1.538245e+12   
75%     4.570000    25.000000     0.590000    56.000000  1.538766e+12   
max     9.120000   172.000000     1.910000  2015.000000  1.539475e+12   

           tsunami           tz       updated  
count  9332.000000  9331.000000  9.332000e+03  
mean      0.006537  -451.990140  1.538537e+12  
std       0.080589   231.752571  6.564135e+08  
min       0.000000  -720.000000  1.537230e+12  
25%       0.000000  -540.000000  1.537996e+12  
50%       0.000000  -480.000000  1.538621e+12  
75%       0.000000  -480.000000  1.539110e+12  
max       1.000000   720.000000  1.539537e+12

In [20]:
df.dmin.mean()

0.5449252750773741

In [30]:
df.gap.nunique()

1114

In [31]:
df.tsunami.unique()

array([0, 1])

# Practice of Thursday

In [21]:
import pandas as pd
import numpy as np

In [22]:
profile = pd.DataFrame({'name': ['LeeSeungYoon','JeongJongOh','Fernan Migo'],
                        'hobby': ['music','movie','video game'],
                        'nationallity':['kor','kor','france'],
                        'rand_num' : np.random.rand(3)*100
                        })

In [23]:
profile

name       hobby nationallity   rand_num
0  LeeSeungYoon       music          kor  60.710962
1   JeongJongOh       movie          kor  57.713609
2   Fernan Migo  video game       france   1.649571

In [24]:
profile = profile.set_index('name')

In [25]:
profile

hobby nationallity   rand_num
name                                            
LeeSeungYoon       music          kor  60.710962
JeongJongOh        movie          kor  57.713609
Fernan Migo   video game       france   1.649571

In [26]:
profile.to_csv("ex.csv",index = False)

In [27]:
profile.rand_num.mean()

40.02471419658783

In [28]:
data_ex = pd.read_csv("ex.csv")

In [29]:
data_ex

hobby nationallity   rand_num
0       music          kor  60.710962
1       movie          kor  57.713609
2  video game       france   1.649571